server:
  address: 0.0.0.0
  port: 8080

schema:
  topic: "_schemas"
  groupId: group.schema

  datasource:
    url: jdbc:h2:mem:schemadb
    driverClassName: org.h2.Driver
    username: sa
    password: j2lab123$
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
